services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=megabike'
      - 'POSTGRES_PASSWORD=megabike'
      - 'POSTGRES_USER=megabike'
    ports:
      - '5433:5432'
    volumes:
      - 'megabike-postgres-data:/var/lib/postgresql/data'

volumes:
  megabike-postgres-data:
